"""
Wireframe Component Models

These Pydantic models define the structure of UI components that flow through the system:

    CV/OpenCV → Component JSON → React Frontend
    Gemini    → Component JSON → React Frontend

Your teammate's React frontend will receive these JSON structures and render them.

COMPONENT TYPES (17 types - what we can detect/generate):

Navigation:
- NAVBAR: Navigation bar at top
- SIDEBAR: Vertical navigation (desktop)
- FOOTER: Bottom section
- BOTTOM_NAV: Mobile bottom navigation

Content Sections:
- HERO: Large banner section with headline
- SECTION: Generic content section
- CARD: Content card (often in grids)

Interactive Elements:
- FORM: Input form with fields
- BUTTON: Clickable button
- INPUT: Single input field

Text Elements:
- TEXT: Text block/paragraph
- HEADING: Title/heading text

Media & Data:
- IMAGE: Image placeholder
- TABLE: Data table
- CALENDAR: Calendar widget
- CHART: Chart/graph placeholder

Frames:
- FRAME: Device container (macbook, iphone)
"""

from typing import Optional, Literal
from pydantic import BaseModel, Field
from enum import Enum
import uuid


class ComponentType(str, Enum):
    """
    All possible component types we can detect from sketches or generate via LLM.

    Total: 17 component types

    When adding new types:
    1. Add here
    2. Update CV shape mapping in vision/detect.py
    3. Update LLM prompts in llm/prompts.py
    4. Tell your teammate to add React component
    """
    # Navigation
    NAVBAR = "NAVBAR"
    SIDEBAR = "SIDEBAR"
    FOOTER = "FOOTER"
    BOTTOM_NAV = "BOTTOM_NAV"  # Mobile bottom navigation

    # Content sections
    HERO = "HERO"
    SECTION = "SECTION"
    CARD = "CARD"

    # Interactive elements
    FORM = "FORM"
    BUTTON = "BUTTON"
    INPUT = "INPUT"

    # Text elements
    TEXT = "TEXT"
    HEADING = "HEADING"

    # Media & Data
    IMAGE = "IMAGE"
    TABLE = "TABLE"
    CALENDAR = "CALENDAR"
    CHART = "CHART"

    # Frames (device containers)
    FRAME = "FRAME"


class Position(BaseModel):
    """
    Position on the canvas (in pixels from top-left).
    React frontend will use these for absolute positioning or grid placement.
    """
    x: float = Field(description="Pixels from left edge")
    y: float = Field(description="Pixels from top edge")


class Size(BaseModel):
    """
    Dimensions of a component.
    Can be pixels or percentage strings like "100%" for full width.
    """
    width: float | str = Field(description="Width in pixels or '100%'")
    height: float | str = Field(description="Height in pixels or 'auto'")


class Component(BaseModel):
    """
    A single UI component in the wireframe.

    
    This is the core data structure that:
    - CV/OpenCV outputs when detecting shapes in sketches
    - Gemini outputs when generating layouts
    - React frontend receives to render on canvas

    
    Example:
        {
            "id": "comp_abc123",
            "type": "NAVBAR",
            "position": {"x": 0, "y": 0},
            "size": {"width": "100%", "height": 60},
            "props": {
                "logo": "My App",
                "links": ["Home", "About", "Contact"]
            },
            "confidence": 0.95  # If detected by CV
        }
    """
    id: str = Field(
        default_factory=lambda: f"comp_{uuid.uuid4().hex[:8]}",
        description="Unique identifier for this component"
    )
    type: ComponentType = Field(description="Type of UI component")
    position: Position = Field(description="Where on canvas")
    size: Size = Field(description="Width and height")
    props: dict = Field(
        default_factory=dict,
        description="Component-specific properties (text, colors, etc)"
    )
    confidence: Optional[float] = Field(
        default=None,
        description="CV detection confidence (0-1), None if generated by LLM"
    )
    z_index: int = Field(
        default=0,
        description="Stacking order for overlapping components"
    )


class LayoutType(str, Enum):
    """Layout arrangement for the wireframe"""
    SINGLE_COLUMN = "single-column"
    TWO_COLUMN = "two-column"
    SIDEBAR_LEFT = "sidebar-left"
    SIDEBAR_RIGHT = "sidebar-right"
    GRID = "grid"
    FREEFORM = "freeform"


class Wireframe(BaseModel):
    """
    Complete wireframe containing multiple components.

    
    This is what gets sent to React frontend:
        {
            "id": "wf_xyz789",
            "name": "Student Club Landing",
            "layout": "single-column",
            "canvas_size": {"width": 1200, "height": 800},
            "components": [
                {"id": "comp_1", "type": "NAVBAR", ...},
                {"id": "comp_2", "type": "HERO", ...},
                ...
            ]
        }
    """
    id: str = Field(
        default_factory=lambda: f"wf_{uuid.uuid4().hex[:8]}",
        description="Unique wireframe ID"
    )
    name: str = Field(
        default="Untitled Wireframe",
        description="Human-readable name"
    )
    layout: LayoutType = Field(
        default=LayoutType.SINGLE_COLUMN,
        description="Overall layout arrangement"
    )
    canvas_size: Size = Field(
        default_factory=lambda: Size(width=1200, height=800),
        description="Canvas dimensions"
    )
    components: list[Component] = Field(
        default_factory=list,
        description="All components in this wireframe"
    )

    def add_component(self, component: Component) -> None:
        """Add a component to the wireframe"""
        self.components.append(component)

    
    def add_component(self, component: Component) -> None:
        """Add a component to the wireframe"""
        self.components.append(component)
    
    def remove_component(self, component_id: str) -> bool:
        """Remove component by ID, returns True if found"""
        for i, comp in enumerate(self.components):
            if comp.id == component_id:
                self.components.pop(i)
                return True
        return False

    
    def get_component(self, component_id: str) -> Optional[Component]:
        """Get component by ID"""
        for comp in self.components:
            if comp.id == component_id:
                return comp
        return None

    
    def to_json(self) -> dict:
        """Convert to JSON-serializable dict for React frontend"""
        return self.model_dump()


# =============================================================================
# ADDITIONAL MODELS FOR GEMINI/CV PIPELINE
# =============================================================================

class BoundingBox(BaseModel):
    """Bounding box for detected shapes in CV pipeline."""
    x: float = Field(description="Top-left X coordinate")
    y: float = Field(description="Top-left Y coordinate")  
    width: float = Field(description="Width in pixels")
    height: float = Field(description="Height in pixels")
    
    @property
    def center(self) -> tuple:
        return (self.x + self.width / 2, self.y + self.height / 2)


class DetectedText(BaseModel):
    """Text detected via OCR in sketches."""
    text: str = Field(description="The detected text content")
    bounding_box: BoundingBox = Field(description="Where the text was found")
    confidence: float = Field(default=0.0, description="OCR confidence 0-1")


class WireframeComponent(BaseModel):
    """
    Component for WireframeLayout - matches Gemini output format.
    Similar to Component but with additional fields for LLM pipeline.
    """
    id: str = Field(
        default_factory=lambda: f"comp_{uuid.uuid4().hex[:8]}",
        description="Unique identifier"
    )
    type: str = Field(description="Component type (NAVBAR, HERO, etc.)")
    position: Position = Field(description="Position on canvas")
    size: Size = Field(description="Width and height")
    props: dict = Field(default_factory=dict, description="Component properties")
    children: list = Field(default_factory=list, description="Nested components")
    source: str = Field(default="llm", description="Where this came from: llm, cv, user")
    confidence: Optional[float] = Field(default=None, description="Detection confidence")
    order: Optional[int] = Field(default=None, description="Render order")


class WireframeLayout(BaseModel):
    """
    Full wireframe layout - matches Gemini JSON output format.
    This is the main model used by generation pipeline.
    """
    id: str = Field(
        default_factory=lambda: f"layout_{uuid.uuid4().hex[:8]}",
        description="Unique layout ID"
    )
    name: str = Field(default="Untitled", description="Layout name")
    canvas_size: Size = Field(
        default_factory=lambda: Size(width=1440, height=900),
        description="Canvas dimensions"
    )
    background_color: str = Field(default="#ffffff", description="Background color")
    source_type: str = Field(default="prompt", description="How it was created: prompt, sketch, mockup")
    components: list[WireframeComponent] = Field(
        default_factory=list,
        description="All components in layout"
    )
    
    def to_json(self) -> dict:
        """Convert to JSON-serializable dict"""
        return self.model_dump()


class CVDetectionResult(BaseModel):
    """Result from CV/OpenCV sketch analysis."""
    components: list[WireframeComponent] = Field(
        default_factory=list,
        description="Detected components"
    )
    detected_text: list[DetectedText] = Field(
        default_factory=list,
        description="OCR results"
    )
    original_size: Size = Field(
        default_factory=lambda: Size(width=0, height=0),
        description="Original image dimensions"
    )
    debug_image_base64: Optional[str] = Field(
        default=None,
        description="Debug visualization as base64"
    )
    processing_notes: list[str] = Field(
        default_factory=list,
        description="Processing log"
    )


# Component templates for default props (17 types)
COMPONENT_TEMPLATES: dict = {
    # Navigation
    "NAVBAR": {"logo": "Logo", "links": ["Home", "About", "Contact"], "cta": "Sign Up"},
    "SIDEBAR": {"items": ["Dashboard", "Settings", "Profile"]},
    "FOOTER": {"links": ["Privacy", "Terms", "Contact"], "copyright": "© 2024"},
    "BOTTOM_NAV": {"items": ["Home", "Search", "Profile", "Settings"]},

    # Content sections
    "HERO": {"headline": "Your Headline Here", "subheadline": "Supporting text", "cta": "Get Started"},
    "SECTION": {"title": "Section Title", "content": "Section content goes here"},
    "CARD": {"title": "Card Title", "content": "Card content goes here"},

    # Interactive elements
    "FORM": {"fields": [{"label": "Email", "type": "email"}], "submit": "Submit"},
    "BUTTON": {"label": "Button", "variant": "primary"},
    "INPUT": {"placeholder": "Enter text...", "type": "text"},

    # Text elements
    "TEXT": {"content": "Text content here"},
    "HEADING": {"text": "Heading", "level": 1},

    # Media & Data
    "IMAGE": {"alt": "Image placeholder", "src": ""},
    "TABLE": {"columns": ["Name", "Email", "Status"], "rows": 5},
    "CALENDAR": {"view": "month"},
    "CHART": {"type": "bar", "title": "Chart Title"},

    # Frames
    "FRAME": {"device": "macbook", "width": 1440, "height": 900},
}
